"""empty message

Revision ID: 3f79733c333a
Revises: aaa059a1766
Create Date: 2016-11-12 04:00:03.970891

"""

# revision identifiers, used by Alembic.
revision = '3f79733c333a'
down_revision = 'aaa059a1766'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
