"""empty message

Revision ID: 40aaa56f380f
Revises: None
Create Date: 2016-11-10 19:01:43.667857

"""

# revision identifiers, used by Alembic.
revision = '40aaa56f380f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
