"""empty message

Revision ID: 592748915121
Revises: 40aaa56f380f
Create Date: 2016-11-12 02:54:22.308022

"""

# revision identifiers, used by Alembic.
revision = '592748915121'
down_revision = '40aaa56f380f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
