"""empty message

Revision ID: aaa059a1766
Revises: 592748915121
Create Date: 2016-11-12 03:29:06.456992

"""

# revision identifiers, used by Alembic.
revision = 'aaa059a1766'
down_revision = '592748915121'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
